districts_subdistricts_dict = {
    "praga polnoc": [
        "nowa praga",
        "pelcowizna",
        "stara praga",
        "szmulowizna",
        "sliwice",
        "goledzinow",
        "michalow",
        'praga-polnoc'
    ],
    "praga poludnie": [
        "goclaw",
        "goclawek",
        "grochow",
        "kamionek",
        "olszynka grochowska",
        "saska kepa",
        "kepa goclawska",
        "witolin",
        "kozia gorka",
        'praga-poludnie',
        'praga-poludnie	'
    ],
    "targowek": [
        "elsnerow",
        "brodno",
        "brodno podgrodzie",
        "targowek fabryczny",
        "targowek mieszkaniowy",
        "zacisze",
        "utrata",
        "nowe brodno",
        "stare brodno",
        "lewinow",
        "lasek brodnowski",
        'brodno-podgrodzie'
    ],
    "zoliborz": [
        "marymont potok",
        "stary zoliborz",
        "sady zoliborskie",
        "zoliborz dziennikarski",
        "zoliborz oficerski",
        "zoliborz urzedniczy",
        "zatrasie",
        "powazki"
    ],
    "bielany": [
        "chomiczowka",
        "huta",
        "las bielanski",
        "mlociny",
        "marymont kaskada",
        "marymont ruda",
        "piaski",
        "placowka",
        "radiowo",
        "slodowiec",
        "stare bielany",
        "wolka weglowa",
        "wawrzyszew",
        "wrzeciono",
        "stary wawrzyszew"
    ],
    "wilanow": [
        "wilanow wysoki",
        "wilanow niski",
        "wilanow krolewski",
        "blonia wilanowskie",
        "powsinek",
        "zawady",
        "kepa zawadowska",
        "powsin",
        "nadwilanowka",
        "nadwislanka",
        "bartyki",
        "zamosc",
        "latoszki",
        "lisy",
        "kepa latoszkowa",
        "wolica",
        "park natolinski",
        "morysin",
        "nowy wilanow",
        'miasteczko wilanow'
    ],
    "bialoleka": [
        "bialoleka dworska",
        "brzeziny",
        "choszczowka",
        "dabrowka szlachecka",
        "grodzisk",
        "henrykow",
        "kobialka",
        "nowodwory",
        "szamocin",
        "tarchomin",
        "zeran",
        "tarchomin koscielny",
        "winnica",
        "kepa tarchominska",
        "kalenica",
        "buchnik",
        "bukow",
        "nowy tarchomin",
        "anecin",
        "nowe swidry",
        "pludy",
        "wisniewo",
        "stare swidry",
        "piekielko",
        "tarchomin fabryczny",
        "zeran wschodni",
        "annopol",
        "marcelin",
        "dabrowka grzybowska",
        "michalowek",
        "tomaszew",
        "ruskowy brod",
        "olesin",
        "manki wojdy",
        "augustowek",
        "katy grodziskie",
        "lewandow",
        "augustow",
        "konstantynow",
        "aleksandrow"
    ],
    "rembertow": [
        "kaweczyn wygoda",
        "nowy rembertow",
        "stary rembertow",
        "czaplowizna",
        "karolowka",
        "magent",
        "mokry lug",
        "nowa wygoda",
        "zygmuntow",
        "kolonia oficerska",
        'kaweczyn-wygoda'
    ],
    "srodmiescie": [
        "muranow",
        "nowe miasto",
        "powisle",
        "solec",
        "stare miasto",
        "srodmiescie polnocne",
        "srodmiescie poludniowe",
        "ujazdow",
        "mariensztat",
        "mdm",
        "za zelazna brama",
        "starowka",
        'centrum'
    ],
    "bemowo": [
        'lotnisko',
        "bemowo lotnisko",
        "boernerowo",
        "chrzanow",
        "fort bema",
        "fort radiowo",
        "gorce",
        "groty",
        'jelonki',
        "jelonki polnocne",
        "jelonki poludniowe",
        "nowe bemowo",
        "stare bemowo",
        "stare gorce",
        "nowe gorce",
        "na wyraju",
        "mory",
        "karolin",
        "osiedle przyjazn"
    ],
    "ursynow": [
        "dabrowka",
        "grabow",
        "jeziorki polnocne",
        "jeziorki poludniowe",
        "kabaty",
        "natolin",
        "pyry",
        "skarpa powsinska",
        "stary sluzew",
        "stary imielin",
        "rezerwat las kabacki",
        "ursynow centrum",
        "ursynow polnocny",
        "wyczolki",
        "jeziorki polskie",
        "jeziorki nowe",
        "dawidy",
        "ludwinow",
        "krasnowola",
        "grabowek",
        "janowek",
        "leczyca",
        "kierszek",
        "wyzyny",
        "czesc wolicy",
        "na skraju",
        "czesc imielina",
        "jary",
        "stoklosy",
        "zakopane",
        'imielin'
    ],
    "mokotow": [
        "augustowka",
        "czerniakow",
        "ksawerow",
        "sluzew",
        "sluzewiec",
        "sadyba",
        "siekierki",
        "sielce",
        "stary mokotow",
        "stegny",
        "wierzbno",
        "wygledow",
        'mokotow grupy',
        'pole mokotowskie',
        'gorny mokotow',
        'dolny mokotow',
        'marina mokotow'
    ],
    "ochota": [
        "filtry",
        "rakowiec",
        "stara ochota",
        "szczesliwice",
        "kolonia staszica",
        "kolonia lubeckiego"
    ],
    "ursus": [
        "czechowice",
        "golabki",
        "niedzwiadek",
        "skorosze",
        "szamoty"
    ],
    "wawer": [
        "aleksandrow",
        "anin",
        "falenica",
        "las",
        "marysin wawerski",
        "miedzeszyn",
        "miedzylesie",
        "nadwisle",
        "radosc",
        "sadul",
        "wawer",
        "zerzen",
        "stary anin",
        "nowy anin",
        "blota",
        "zatrzebie",
        "stary wawer",
        "elzbietowek",
        "nowy miedzeszyn",
        "zagozdz",
        "wisniowa gora",
        "szelagowizna",
        "czesc borkowa",
        "julianow",
        "skrzyki",
        "wolka zerzenska",
        "miedzeszyn wies",
        "zbojna gora",
        "zastow",
        "zbytki",
        "kuligow",
        "nowy wawer"
    ],
    "wesola": [
        "groszowka",
        "plac wojska polskiego",
        "stara milosna",
        "wesola centrum",
        "wola grzybowska",
        "zielona grzybowa",
        'wesola-centrum'
    ],
    "wlochy": [
        "nowe wlochy",
        "okecie",
        "opacz wielka",
        "paluch",
        "rakow",
        "salomea",
        "stare wlochy",
        "zaluski",
        "jadwisin",
        "zbarz",
        "gorzkiewki",
        "budki szczesliwickie",
        "solipse"
    ],
    "wola": [
        "czyste",
        "kolo",
        "mlynow",
        "mirow",
        "nowolipki",
        "odolany",
        "powazki",
        "ulrychow",
        "park moczydlo",
        "osiedle kolo",
        'nowolipie',
        'moczydlo'
    ]
}

